### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by szepeviktor**
@chesio the most shocking PR of the century.

Please use `typos`.

### CODE REVIEW

**Comment by chesio** [comment]
> @chesio the most shocking PR of the century.

Thanks! :-)

> Please use `typos`.

Do you mean https://github.com/crate-ci/typos ?

**Comment by szepeviktor** [comment]
Yes. It will spot `UDPATE`.

**Comment by szepeviktor** [comment]
In 7 years no one used the `unlockMany` method?
Or error handling hid the problem?

**Comment by chesio** [comment]
> In 7 years no one used the `unlockMany` method? Or error handling hid the problem?

Well, it's not that surprising :-) No one is most likely just me, I don't think the plugin has many users ;-)

**Pull request merged**
