### PR TITLE
PHPStan +wordpress-stubs has sharper eye than we

### PR DESCRIPTION
**Pull request by szepeviktor**
@chesio Please do review PHPStan's findings!!

I suggest you to use it every day.

### CODE REVIEW

**Comment by szepeviktor** [comment]
If you decide to continue, phpstan will reveal further perls

```
 ------ --------------------------------------------------------------------------------------------------------------
  Line   BlueChip/Security/Core/ListTable.php
 ------ --------------------------------------------------------------------------------------------------------------
  129    Parameter #1 $item (array) of method BlueChip\Security\Core\ListTable::column_cb() should be compatible with
         parameter $item (object) of method WP_List_Table::column_cb()
  142    Parameter #1 $item (array) of method BlueChip\Security\Core\ListTable::column_default() should be compatible
         with parameter $item (object) of method WP_List_Table::column_default()
 ------ --------------------------------------------------------------------------------------------------------------

 ------ ------------------------------------------------------------------------------------------
  Line   BlueChip/Security/Modules/Checklist/Helper.php
 ------ ------------------------------------------------------------------------------------------
  114    Argument of an invalid type stdClass supplied for foreach, only iterables are supported.
 ------ ------------------------------------------------------------------------------------------

 ------ ---------------------------------------------------------------------------------------
  Line   BlueChip/Security/Modules/Checklist/Manager.php
 ------ ---------------------------------------------------------------------------------------
  160    Method BlueChip\Security\Modules\Checklist\Manager::getAdvancedChecks() should return
         array<BlueChip\Security\Modules\Checklist\AdvancedCheck> but returns
         array<BlueChip\Security\Modules\Checklist\Check>.
 ------ ---------------------------------------------------------------------------------------
```

**Comment by chesio** [comment]
Hi @szepeviktor,

Thanks a lot for such batch of fixes! And thanks for the PHPStan tip - I'll definitely add PHPStan to the project (and my other projects too) :)

**Comment by szepeviktor** [comment]
You're welcome.

Please consider contributing code to PHPStan.

**Comment by chesio** [comment]
I will, although I'm not an expert on PHP Reflection and related topics. But it's very interesting stuff.

**Comment by szepeviktor** [comment]
@chesio Could it be that my request for quote email does not reach you at przywara.cz?

**Pull request merged**
