### PR TITLE
Remove core function from bootstrap.php

### PR DESCRIPTION
**Pull request by szepeviktor**
Already included in latest WP core stubs.

From https://github.com/chesio/bc-security/actions/runs/7745557030/job/21121844739

### CODE REVIEW

**Comment by szepeviktor** [comment]
Now PHPStan runs!

**Comment by chesio** [comment]
> Already included in latest WP core stubs.

Thanks Viktor! As always 😃

**Comment by chesio** [comment]
> Now PHPStan runs!
> 
> `$wpdb->get_results` got updated recently. [php-stubs/wordpress-stubs#146](https://github.com/php-stubs/wordpress-stubs/pull/146)

I'll check that out...

**Comment by szepeviktor** [comment]
Glad to contribute.

**Pull request merged**
